desc "Train the classifier using the word list"
task :train => :environment do

  word_list = <<-EOF
  amazed            1        6       10
  ardent            1        6       11
  bliss             1        5        4
  calm              1        4       14
  carefree          1        8       10
  cheer             1        5       10
  cheerful          1        8       10
  devoted           1        7       37
  eager             1        5       27
  enjoying          1        8       17
  excited           1        7       21
  faithful          1        8       10
  friendly          1        8       61
  glorious          1        8       16
  happiness         1        9       23
  happy             1        5       97
  hopeful           1        7       12
  hug               1        3        1
  humerous          1        8       16
  joke              1        4       27
  joy               1        3       47
  laugh             1        5       22
  lively            1        6       22
  love              1        4      145
  medal             1        5       11
  peaceful          1        8       26
  pleasant          1        8       35
  pleased           1        7       30
  proud             1        5       50
  relieved          1        8       21
  smile             1        5       56
  sparkle           1        7        4
  stamina           1        7        2
  tender            1        6       11
  trust             1        5       32
  vitality          1        8       17
  warmth            1        6       28
  abuse             2        5       22
  alienation        2       10       22
  ashamed           2        7       17
  avoided           2        7       19
  awful             2        5       14
  bad               2        3      134
  bankrupt          2        8        3
  blame             2        5       34
  bored             2        5       11
  burden            2        6       44
  cramp             2        5        4
  cry               2        3       64
  curse             2        5       10
  damage            2        6       28
  depressed         2        9       11
  despair           2        7       20
  desperate         2        9       26
  doom              2        4       10
  doubts            2        6       16
  dud               2        3        2
  failure           2        7       93
  feeble            2        6        8
  fright            2        6        2
  funeral           2        7       27
  gloom             2        5       14
  grave             2        5       19
  grief             2        5       10
  guilt             2        5       33
  guilty            2        6       29
  helpless          2        8       21
  hopeless          2        8       14
  hurt              2        4       31
  ill               2        3       26
  isolated          2        8       35
  lonely            2        6       25
  loss              2        4       86
  misery            2        6       17
  pathetic          2        8        8
  penalty           2        7       18
  poverty           2        7       20
  punish            2        6       14
  regret            2        6        6
  rejected          2        8       21
  sad               2        3       35
  sick              2        4       51
  solemn            2        6       12
  sorry             2        5       47
  stupid            2        6       24
  suffering         2        9       14
  suicide           2        7       19
  tears             2        5       34
  terrible          2        8       44
  torture           2        7        4
  tragedy           2        7       48
  tragic            2        6       33
  trap              3        4       27
  trouble           2        7      131
  ugly              2        4       21
  unhappy           2        7       26
  upset             2        5       16
  waste             2        5       33
  weakness          2        8       52
  widowed           2        7        5
  worry             2        5       27
  abandoned         3        9       25
  accident          3        8       33
  accuse            3        6       10
  ache              3        4       11
  afraid            3        6       37
  anxiety           3        7       39
  anxious           3        7       29
  bomb              3        4        3
  brooding          3        8       14
  conflict          3        8       51
  confused          3        8       40
  corpse            3        6        7
  crime             3        5       32
  crisis            3        6       77
  danger            3        6       86
  demands           3        7       12
  died              3        4       86
  fearful           3        7       13
  forgotton         3        9       37
  fright            3        6        3
  frightened        3       10       26
  gun               3        3        1
  harm              3        4        1
  inhibit           3        7       17
  injury            3        6       27
  intense           3        7       40
  killed            3        6       75
  murder            3        6       70
  nerves            3        6       22
  nervous           3        7       24
  ominous           3        7       12
  pain              3        4      102
  panic             3        5       20
  restless          3        8       13
  risk              3        4       42
  scared            3        6       18
  shock             3        5       30
  shocked           3        7       17
  shy               3        3       11
  suffer            3        6       33
  tense             3        5       10
  tension           3        7       58
  terror            3        6       26
  threat            3        7       56
  threat            3        6       42
  torture           3        7       10
  trap              3        4       19
  troubled          3        8       23
  uneasy            3        6       23
  urgent            3        6       21
  victim            3        6       27
  violence          3        8       44
  warning           3        7       17
  absorb            4        6       41
  academy           4        7       28
  account           4        7      114
  acquaint          4        8       15
  agency            4        6       48
  aluminum          4        8       18
  average           4        7        5
  banana            4        6        4
  barbecue          4        8       15
  bathe             4        5       26
  brandy            4        6        7
  bread             4        5       41
  buck              4        4       10
  bus               4        3       34
  butter            4        6       27
  butterfly         4        9        2
  chicken           4        7       49
  civilian          4        8       10
  concert           4        7       35
  conclude          4        8       16
  context           4        7       37
  cousin            4        6       13
  cup               4        3       44
  customers         4        9       41
  deduct            4        6       17
  degrees           4        7       23
  diplomats         4        9        6
  documentary       4       11        4
  dune              4        4        9
  dutch             4        5       11
  earring           4        7        3
  ebony             4        5        3
  eel               4        3        2
  factory           4        7       56
  fan               4        3       34
  fathom            4        6        3
  flame             4        5       27
  fluid             4        5       21
  followed          4        8      172
  fragment          4        8       16
  gateway           4        7        4
  gear              4        4       28
  gene              4        4       11
  glanced           4        7       25
  grass             4        5       55
  green             4        5       85
  grouped           4        7        5
  handle            4        6       22
  hat               4        3       55
  heel              4        4       41
  herd              4        4       26
  hypothesis        4       10       22
  inch              4        4       39
  incline           4        7       21
  indirect          4        8       21
  installed         4        9       35
  iron              4        4       37
  jacket            4        6       39
  juice             4        5       13
  kitty             4        5       12
  ladder            4        6       28
  lawn              4        4       20
  lens              4        4       17
  library           4        7       20
  liquid            4        6       34
  lock              4        4       63
  lunch             4        5       33
  maple             4        6       10
  margin            4        6       16
  measure           4        7       88
  mention           4        7       18
  moth              4        4        1
  nearby            4        6       21
  neutral           4        7       32
  novel             4        5       59
  onion             4        5       19
  orange            4        6        9
  oyster            4        7       16
  package           4        7       14
  palm              4        4       30
  parking           4        7        4
  pave              4        4        2
  pen               4        3       18
  pianist           4        7       21
  placed            4        6      126
  porch             4        5       45
  pottery           4        7       16
  quarter           4        7       62
  quote             4        5       48
  recruit           4        7       17
  refund            4        6       24
  replace           4        7       87
  resident          4        8       28
  restore           4        7       28
  retained          4        8       18
  salad             4        5       12
  sandwich          4        8       13
  scan              4        4       17
  signal            4        6       87
  slope             4        5       19
  solar             4        5       16
  somehow           4        7       72
  sooner            4        7       17
  starling          4        8        1
  steel             4        5       38
  submarine         4        9       15
  swimming          4        8       37
  taste             4        5       58
  temperature       4       12      134
  throw             4        5       35
  total             4        5       25
  transfer          4        8       43
  tray              4        4       21
  vitamin           4        7       15
  wagon             4        5       72
  weekly            4        6       14
  whatever          4        8      111
  willow            4        6       10
  wrist             4        5       16
  writing           4        7       55
  yard              4        4       33
  zero              4        4       17
  zone              4        4       14
  EOF

  valences = { '1' => 'positive', '2' => 'negative', '3' => 'anxious', '4' => 'neutral' }

  word_list.each_line do |line|
    items = line.split(' ')
    p items
    next if items[1] == '3'

    valence = valences[items[1]]
    next unless valence

    puts "Training '#{items[0]}' as #{valence}"

    StatusClassifier.train(valence, items[0])
  end

end
