development:
  adapter: mysql
  database: emo_development
  username: root
  password: 
test:
  adapter: mysql
  database: emo_test
  username: root
  password: xerces270
production:
  adapter: mysql
  database: emo_production
  username: root
  password: xerces270
